#!/usr/bin/env bash

## launch alacritty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/alacritty/alacritty.yml"

if [ "$1" == "--float" ]; then
	#alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG"
    alacritty --class 'alacritty-float,alacritty-float'
elif [ "$1" == "--full" ]; then
	#alacritty --class 'Fullscreen,Fullscreen' --config-file "$CONFIG" \
    alacritty --class 'Fullscreen,Fullscreen' \
			  -o window.startup_mode=fullscreen \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
elif [ "$1" == "--pseudo" ]; then
    alacritty --class 'pseudo_tiled'
else
#	alacritty --config-file "$CONFIG"
    alacritty
fi
