$wallpaper = /home/system/Pictures/wallpapers/a_train_tracks_in_a_foggy_day.jpg
$background = rgb(000000)
$foreground = rgb(D8E4F4)
$cursor = rgb(9EABBC)
$color0 = rgb(000000)
$color1 = rgb(747B83)
$color2 = rgb(6C788A)
$color3 = rgb(6F7C8F)
$color4 = rgb(6A798E)
$color5 = rgb(7F9BBF)
$color6 = rgb(90B2DE)
$color7 = rgb(BFD0E6)
$color8 = rgb(8692A1)
$color9 = rgb(747B83)
$color10 = rgb(6C788A)
$color11 = rgb(6F7C8F)
$color12 = rgb(6A798E)
$color13 = rgb(7F9BBF)
$color14 = rgb(90B2DE)
$color15 = rgb(BFD0E6)
