$wallpaper = /usr/share/backgrounds/nature/nature-11.jpg
$background = rgb(040000)
$foreground = rgb(F6E5CA)
$cursor = rgb(AD9B83)
$color0 = rgb(0F0B05)
$color1 = rgb(867567)
$color2 = rgb(877968)
$color3 = rgb(E06B4D)
$color4 = rgb(E06B4D)
$color5 = rgb(BA9359)
$color6 = rgb(E5B468)
$color7 = rgb(EAD1AB)
$color8 = rgb(A49278)
$color9 = rgb(867567)
$color10 = rgb(877968)
$color11 = rgb(E06B4D)
$color12 = rgb(E06B4D)
$color13 = rgb(BA9359)
$color14 = rgb(E5B468)
$color15 = rgb(EAD1AB)
