max-gamma = 150

profile {
    time = 7:30
    identity = true
}

profile {
    time = 20:00
    temperature = 5500
}

profile {
    time = 21:00
    temperature = 5000
}

profile {
    time = 22:00
    temperature = 4500
}

profile {
    time = 22:30
    temperature = 4000
}

profile {
    time = 23:00
    temperature = 3500
}

profile {
    time = 24:00
    temperature = 3000
}

profile {
    time = 1:00
    temperature = 2700
}

