# Translate engine
Engine=Native
# OpenCC profile for Simplified to Traditional
OpenCCS2TProfile=default
# OpenCC profile for Traditional to Simplified
OpenCCT2SProfile=default

[Hotkey]
0=Control+Alt+Shift+Super+T

[EnabledIM]
0=pinyin

