# Candidates Per Page
# PageSize=5
# Number of Predictions
# PredictionSize=10
# Enable Prediction
# Prediction=False
# Number of Sentences
# Number of sentence=2
# Use Inner Segment
# InnerSegment=True

[PrevPage]
0=Control+K

[NextPage]
0=Control+J

[PrevCandidate]
0=Control+H

[NextCandidate]
0=Control+L

