[window]
opacity = 0.25

[colors.primary]
background = '{{background}}'
foreground = '{{foreground}}'

[colors.cursor]
text = '{{foreground}}'
cursor = '{{cursor}}'

[colors.normal]
black   = '{{color0}}'
red     = '{{color1}}'
green   = '{{color2}}'
yellow  = '{{color3}}'
blue    = '{{color4}}'
magenta = '{{color5}}'
cyan    = '{{color6}}'
white   = '{{color7}}'

[colors.bright]
black   = '{{color8}}'
red     = '{{color9}}'
green   = '{{color10}}'
yellow  = '{{color11}}'
blue    = '{{color12}}'
magenta = '{{color13}}'
cyan    = '{{color14}}'
white   = '{{color15}}'
