backend = "full"
palette = "dark"
color_space = "lchmixed"
# check_contrast = true

[templates]
hypr.template = "hypr.conf"
hypr.target = "~/.config/hypr/colors.conf"

rofi.template = "rofi.rasi"
rofi.target = "~/.config/rofi/shared/colors.rasi"

swaync.template = "swaync.css"
swaync.target = "~/.config/swaync/colors.css"

waybar.template = "waybar.css"
waybar.target = "~/.config/waybar/colors.css"

xresourcs.template = "Xresources"
xresourcs.target = "~/.Xcolors"

spotify.template = "spotify"
spotify.target = "~/.config/spicetify/Themes/wal/color.ini"

kdeglobal.template = "kdeglobals"
kdeglobal.target = "~/.config/kdeglobals"

kvantum.template = "kvantum.kvconfig"
# kvantum.target = "~/.config/Kvantum/wallust/wallust.kvconfig"
kvantum.target = "~/.config/Kvantum/KvArcDark#/KvArcDark#.kvconfig"

pywal.template = "pywal.json"
pywal.target = "~/.cache/wal/colors.json"

xdpl.template = "xdpl.conf"
xdpl.target = "~/.config/xdg-desktop-portal-luminous/config.toml"



# alacritty.template = "alacritty.toml"
# alacritty.target = "~/.config/alacritty/colorschemes/wallust.toml"
