backend = "full"
palette = "dark"
color_space = "lchmixed"
# check_contrast = true

[templates]
hypr.template = "hypr.conf"
hypr.target = "~/.config/hypr/colors.conf"

rofi.template = "rofi.rasi"
rofi.target = "~/.config/rofi/shared/colors.rasi"

swaync.template = "swaync.css"
swaync.target = "~/.config/swaync/colors.css"

waybar.template = "waybar.css"
waybar.target = "~/.config/waybar/colors.css"

xresourcs.template = "Xresources"
xresourcs.target = "~/.Xcolors"

# spotify.template = "spotify"
# spotify.target = "~/.config/spicetify/Themes/wal/color.ini"
# spicetify.template = "spicetify.ini"
# spicetify.target = "~/.config/spicetify/Themes/wallust/color.ini"

kdeglobal.template = "kdeglobals"
kdeglobal.target = "~/.config/kdeglobals"

kvantum.template = "kvantum.kvconfig"
# kvantum.target = "~/.config/Kvantum/wallust/wallust.kvconfig"
kvantum.target = "~/.config/Kvantum/KvArcDark#/KvArcDark#.kvconfig"

pywal.template = "pywal.json"
pywal.target = "~/.cache/wal/colors.json"

# xdpl.template = "xdpl.conf"
# xdpl.target = "~/.config/xdg-desktop-portal-luminous/config.toml"

# ghostty.template = "ghostty.conf"
# ghostty.target = "~/.config/ghostty/colors.conf"

discord.template = "discord.css"
discord.target = "~/.config/Vencord/themes/wallust.css"

# alacritty.template = "alacritty.toml"
# alacritty.target = "~/.config/alacritty/colorschemes/wallust.toml"

kitty.template = "colors-kitty.conf"
kitty.target = "~/.config/kitty/colors.conf"

# neopywal.template = "colors_neopywal.vim"
# neopywal.target = "~/.cache/wallust/colors_neopywal.vim"
# neopywal.target = "~/.cache/wal/colors-wal.vim"

quickshell.template = "quickshell.qml"
quickshell.target = "~/.config/quickshell/config/WallustColors.qml"
