[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)


# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot"]

[language-server.rustowl]
command = "rustowl"

[language-server.harper]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "git-commit"
language-servers = [ "scls", "gpt", "harper" ]

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "t" }
language-servers = [ "scls", "clangd", "gpt", "harper" ]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "t" }
language-servers = [ "scls", "rust-analyzer", "gpt", "harper" ]

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi-language-server", "pyright", "pylsp", "gpt", "harper" ]

[[language]]
name = "toml"
language-servers = [ "taplo", "tombi", "gpt", "harper" ]
auto-format = true

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "scls", "gpt", "harper" ]
auto-format = true

[[language]]
name = "java"
language-servers = [ "scls", "jdtls", "harper" ]
auto-format = true

[[language]]
name = "qml"
language-servers = [ "scls", "qmlls", "harper" ]
auto-format = true

# [language-server.mdpls]
# command = "/usr/bin/mdpls"
# config = { markdown.preview.auto = true }
