
[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
# WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.7
startup_mode = "Maximized"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 12
y = 12

[[hints.enabled]]
command = "/usr/bin/xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
# post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[general]
live_config_reload = true
import = ["/home/system/.config/alacritty/colors.toml", "/home/system/.config/alacritty/fonts.toml"]
