section: screens
	MacBook-Pro.local:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	arch:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	MacBook-Pro.local:
		right = arch
	arch:
		left = MacBook-Pro.local
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 1024000
	switchDelay = 250
	switchCorners = none 
	switchCornerSize = 0
end

