max_width = 104400000000
use_small_heuristics = "Max"

chain_width = 0
fn_call_width = 0
attr_fn_like_width = 0
array_width = 0
struct_lit_width = 0
struct_variant_width = 0
single_line_if_else_max_width = 0

wrap_comments = true
format_code_in_doc_comments = true
