#!/usr/bin/env bash

tmp_dir="/tmp/cliphist"

if [[ -n "$1" ]]; then
    cliphist decode <<<"$1" | wl-copy
    exit
fi

mkdir -p "$tmp_dir"

read -r -d '' prog <<EOF
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
    system("echo " grp[1] "\\\\\t | cliphist decode >$tmp_dir/"grp[1]"."grp[3])
    print \$0"\0icon\x1f$tmp_dir/"grp[1]"."grp[3]
    next
}
1
EOF
# echo $(cat "$tmp_dir/cliphist")
# format: <id>\t<100 char preview> remove the ID



# cat "$tmp_dir/cliphist"
cliphist list | head -n 100 | gawk "$prog" &
