#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/emoji.rasi"

# Run
rofi \
  -show emoji \
	-theme ${RASI} \
  -kb-secondary-copy "" -kb-accept-entry "" -kb-custom-1 Return
