#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/configs.rasi"

# Theme Elements
mesg="Select configs"

# Options
option_1="ZSH profile(zshrc)"
option_2="ZSH environment(zshenv)"
option_3="Hyprland (hyprland.conf)"
option_4="Hyprland keybind(binds.conf)"
option_5="Polybar config"
option_6="Polybar module"
option_7="Alacritty main config"
option_8="Picom config"
option_9="Directorys"
option_10=".config"
option_11=".local"
option_12="ZSH"
option_13="Hyprland"
option_14="Polybar"
option_15="BPWM-Scripts"
option_16="Scripts"
#option_17="Neovim(lvim)"

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-mesg "$mesg" \
        -case-sensitive \
        -i \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6\n$option_7\n$option_8\n$option_9\n$option_10\n$option_11\n$option_12\n$option_13\n$option_14\n$option_15\n$option_16" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.zshrc
  elif [[ "$1" == '--opt2' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.zshenv
	elif [[ "$1" == '--opt3' ]]; then
		alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/hypr/hyprland.conf
	elif [[ "$1" == '--opt4' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/hypr/binds.conf
	elif [[ "$1" == '--opt5' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/polybar/config.ini
	elif [[ "$1" == '--opt6' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/polybar/modules.ini
  elif [[ "$1" == '--opt7' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/alacritty/alacritty.toml
  elif [[ "$1" == '--opt8' ]]; then
    alacritty --class 'alacritty-float,alacritty-float' --command lvim $HOME/.config/picom.conf
  elif [[ "$1" == '--opt10' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config
  elif [[ "$1" == '--opt11' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.local/share
  elif [[ "$1" == '--opt12' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config/zsh
  elif [[ "$1" == '--opt13' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config/bspwm
  elif [[ "$1" == '--opt14' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config/polybar
  elif [[ "$1" == '--opt15' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config/bspwm/scripts
  elif [[ "$1" == '--opt16' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/scripts
  elif [[ "$1" == '--opt17' ]]; then
    rofi -show filebrowser -theme $HOME/.config/rofi/filebrowser.rasi -file-browser-dir $HOME/.config/lvim
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
    run_cmd --opt6
        ;;
    $option_7)
    run_cmd --opt7
        ;;
    $option_8)
    run_cmd --opt8
        ;;
    $option_10)
    run_cmd --opt10
        ;;
    $option_11)
    run_cmd --opt11
        ;;
    $option_12)
    run_cmd --opt12
        ;;
    $option_13)
    run_cmd --opt13
        ;;
    $option_14)
    run_cmd --opt14
        ;;
    $option_15)
    run_cmd --opt15
        ;;
    $option_16)
    run_cmd --opt16
        ;;
esac
