#!/usr/bin/bash

DIR="$HOME/.config/rofi"
RASI="$DIR/clipboard.rasi"
# rofi -modi clipboard:"$DIR/scripts/cliphist-rofi-img" -show clipboard -theme ${RASI}
cliphist --image "\x00icon\x1f" list | rofi -dmenu -show-icons -theme ${RASI} | cliphist decode | wl-copy
