#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/rofi"
RASI="$DIR/custom_command.rasi"

# Rofi text dialog to get password
sh -c "$(rofi -dmenu \
     -i \
     -p 'Command' \
     -theme ${RASI})"
